"""benji.kit_md — the Claude-ready kit: ONE Markdown brief per role.

Co-owner decision (2026-08-24, day six): the generated .docx resume is
not the deliverable she iterates on — a Claude web chat is. So the kit
becomes a single .md file carrying EVERYTHING that chat needs: the full
job posting, a positioning brief for THIS role built from her real
record, the complete CLEAN v3 source, the register rules and the
DO-NOT-USE list — so the web Claude starts with maximum context and
the same guardrails Benji enforces mechanically.

The positioning intelligence is layered, honest-by-construction:
  * A DETERMINISTIC core computed from coverage: the angle (by org
    type), which of her real roles carry the most required-terms
    weight, the JD vocabulary she already owns, and the gaps — with
    the standing instruction that a gap is addressed honestly or left,
    never invented.
  * An optional LLM narrative on top, drafted from the record only and
    gate-checked (untraceable number / DO-NOT-USE hit → the narrative
    is DROPPED with a flag; the deterministic core always ships).
"""
from __future__ import annotations

from datetime import datetime

from agents.benji.coverage import CoverageReport, _terms
from agents.benji.source_parser import CandidateSource

# Angle by org type — the positioning thesis skeleton (Generation Spec
# voice section + her career narrative, generalized per target type).
_ANGLES = {
    "foundation": (
        "Grantee-side vantage as the offer: she has lived the side of "
        "the table this funder's partners live on — funder reporting, "
        "restricted-fund budgets, mid-cycle course corrections. Name "
        "the gap (never sat on the grantmaking side) and make it the "
        "reason to hire."),
    "tech_csr": (
        "The bridge: computer-science trained, then a decade running "
        "mission-driven delivery. She speaks both rooms — engineering "
        "credibility for the company, operating credibility for the "
        "community partners."),
    "edtech": (
        "Classroom-to-product arc: taught in an under-resourced "
        "classroom, built education programs at scale, then took an "
        "education product into districts. Product decisions grounded "
        "in delivery reality."),
    "nonprofit": (
        "Delivery under contract: owned municipal-contract workstreams "
        "end to end with independent reporting requirements — the "
        "operating discipline intermediaries hire for."),
    "tech_general": (
        "Program leadership with technical fluency: 13 years of "
        "program delivery plus an engineering foundation — reads "
        "technical rooms without translation."),
}


def lead_experiences(source: CandidateSource,
                     required: set[str], jd_terms: set[str],
                     top_roles: int = 3) -> list[dict]:
    """Her roles ranked by overlap with the JD's REQUIRED terms, each
    with its two most relevant real bullets. Pure computation."""
    ranked = []
    for role in source.roles:
        bullets = []
        for b in role.bullets:
            terms = _terms(b)
            bullets.append((len(terms & required), len(terms & jd_terms),
                            b))
        bullets.sort(key=lambda x: (-x[0], -x[1]))
        score = sum(x[0] for x in bullets[:3])
        ranked.append({"role": role, "score": score,
                       "top_bullets": [b for _, _, b in bullets[:2]]})
    ranked.sort(key=lambda r: -r["score"])
    return [r for r in ranked[:top_roles] if r["score"] > 0] or ranked[:1]


def build_claude_kit(*, job: dict, source: CandidateSource,
                     cov: CoverageReport, story: str, story_why: str,
                     org_type: str, leads: list[dict],
                     llm_positioning: str | None,
                     now: datetime) -> str:
    angle = _ANGLES.get(org_type, _ANGLES["nonprofit"])
    jd = (job.get("jd_text") or "").strip() or (
        "(no job description available — READ THE POSTING at the link "
        "above before drafting anything)")
    matched_top = ", ".join(cov.matched[:20]) if cov.matched else "—"
    unmatched_top = ", ".join(cov.unmatched[:15]) if cov.unmatched else "—"

    lead_lines = []
    for i, l in enumerate(leads, 1):
        r = l["role"]
        lead_lines.append(f"{i}. **{r.title} — {r.org}** ({r.dates})")
        for b in l["top_bullets"]:
            lead_lines.append(f"   - {b}")

    parts = [
        f"# Application kit — {job.get('title')} @ {job.get('org')}",
        f"_Generated by Benji · {now.strftime('%Y-%m-%d')} · score "
        f"{job.get('score')} · coverage "
        f"{int(cov.coverage * 100)}%_",
        "",
        "## How to use this file",
        "Upload it to a Claude chat and say what you want — e.g. "
        "\"draft a 2-page ATS-safe resume tailored to this role\" or "
        "\"draft the cover letter\" — then iterate. Everything Claude "
        "needs is below: the posting, the positioning, the complete "
        "verified record, and the rules. **The one rule above all: "
        "reframe, never add.** Every fact, number, title, date and "
        "employer must already exist in the CANDIDATE RECORD section. "
        "If an edit would require a new claim, the answer is no.",
        "",
        "## The role",
        f"- **Org:** {job.get('org')}  ",
        f"- **Title:** {job.get('title')}  ",
        f"- **Apply at:** {job.get('canonical_url')}  ",
        f"- **Location/mode:** {job.get('location') or 'n/a'} · "
        f"{job.get('work_mode') or 'n/a'}  ",
        f"- **Comp:** {job.get('comp_range') or 'unlisted'}  ",
        f"- **Benji score:** {job.get('score')} "
        f"({job.get('rationale', '')})",
        "",
        "### Full job description",
        "```", jd[:12000], "```",
        "",
        "## Positioning for this role",
        f"**The angle ({org_type.replace('_', ' ') or 'general'} "
        f"target):** {angle}",
        "",
        "**Lead with these experiences** (ranked by overlap with the "
        "JD's required qualifications — real bullets, quoted from the "
        "record):",
        "", *lead_lines, "",
        f"**JD vocabulary she already owns** (mirror these words): "
        f"{matched_top}",
        "",
        f"**Gaps — terms the record does not cover:** {unmatched_top}",
        "Handle gaps honestly: cover with genuinely adjacent evidence "
        "if it exists in the record, name the gap and turn it into the "
        "offer (the Hewlett-letter move), or leave it. Never invent, "
        "never stuff keywords into bullets that don't describe her "
        "work.",
        "",
        f"**Story to carry the narrative:** {story} — {story_why}. "
        "One story per letter, facts attached to it rather than listed "
        "separately.",
    ]
    if llm_positioning:
        parts += ["", "### Positioning brief (drafted, gate-checked)",
                  llm_positioning.strip()]
    parts += [
        "",
        "## Hard rules for anything you produce",
        "- Resume: ≤2 pages, single column, ATS-safe (no tables/text "
        "boxes/graphics), ≤5 bullets per role, role order EXACTLY as "
        "in the record, never upgrade a verb past what the record "
        "supports, bullets end on the outcome.",
        "- Letter: 350–450 words, four moves — concrete image opener; "
        "name the gap and make it the offer; something REAL and "
        "specific about this org (if you can't verify one, leave "
        "[ORG-SPECIFIC: fill in]); end on a reason, not a flourish. "
        "Warmer and plainer than the resume.",
        "- The DO-NOT-USE list below is absolute — scan your draft "
        "against it before you finish.",
        "",
        "## CANDIDATE RECORD — the single source of truth "
        "(CLEAN v3, verbatim; includes register rules, story bank, "
        "voice and the DO-NOT-USE list)",
        "", source.raw_text,
    ]
    return "\n".join(parts)
